### ISSUE TITLE
Revision advice for Design Document - Architecture, version1

### ISSUE THREAD

**Issue by Zhuifeng414** [Capstone-Projects-2023-Spring/project-optimap#42]
Good job on creating this design document! It shows a clear understanding of the system and provides a comprehensive overview of the project's architecture. 

The following is advice for further improvement:

1. Please provide a high-level description of your system first. (0.5)

2. Please ensure that each section starts with a number and that subsections begin with sub-numbers (e.g., 1.1, 1.2). Please also check the document formatting. The position of Figure 1.0, Front-end class diagram is not correct, and Figure 1.1, Back-end class diagram appears twice. (0.5)

3. Please add a section on database design. (1.5)

4. Please describe the algorithm in more detail. (1.5)
- How many algorithms are suitable for your project? Please compare them and explain why you chose Dijkstra's algorithm.
- The real road map is a large graph, and sometimes Dijkstra's algorithm cannot run on a single server. How do you handle this situation?
- Various factors such as real-time traffic conditions, road closures, and other obstacles can affect the optimal route. Which one will you choose as the weight?
- The road map and real-time traffic are constantly changing. How will you update your database? And what is your data source?

**Comment by Endri2001** [comment]
I updated the document to meet the criteria above
